# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipfs_lite/dag/pb/dag_pb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ipfs_lite/dag/pb/dag_pb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dipfs_lite/dag/pb/dag_pb.proto\x12\x10ipfs_lite.dag.pb\"3\n\x06PBLink\x12\x0c\n\x04Hash\x18\x01 \x01(\x0c\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\r\n\x05Tsize\x18\x03 \x01(\x04\"?\n\x06PBNode\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\x12\'\n\x05Links\x18\x02 \x03(\x0b\x32\x18.ipfs_lite.dag.pb.PBLink')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipfs_lite.dag.pb.dag_pb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PBLINK']._serialized_start=51
  _globals['_PBLINK']._serialized_end=102
  _globals['_PBNODE']._serialized_start=104
  _globals['_PBNODE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
